name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build backend image
      - name: Build backend image
        run: docker build -t yash5429q/weather-backend:latest ./weather-backend

      # 5. Build frontend image
      - name: Build frontend image
        run: docker build -t yash5429q/weather-frontend:latest ./weather-frontend

      # 6. Run docker-compose for testing
      - name: Run docker-compose
        run: docker-compose up -d

      # 7. Test backend health
      - name: Test backend health
        run: |
          sleep 10
          curl -f http://localhost:4000/health || exit 1

      # 8. Push backend image
      - name: Push backend image
        run: docker push yash5429q/weather-backend:latest

      # 9. Push frontend image
      - name: Push frontend image
        run: docker push yash5429q/weather-frontend:latest

      # 10. Shutdown containers
      - name: Shutdown
        run: docker-compose down
