name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build backend image
      - name: Build backend image
        run: docker build -t backend ./backend

      # 4. Build frontend image
      - name: Build frontend image
        run: docker build -t frontend ./frontend

      # 5. Run docker-compose for testing
      - name: Run docker-compose
        run: docker-compose up -d

      # 6. Test backend health
      - name: Test backend health
        run: |
          sleep 10
          curl -f http://localhost:4000/health || exit 1

      # 7. Shutdown containers
      - name: Shutdown
        run: docker-compose down
